config/routes.rb
Rails.application.routes.draw do
  
  root  'pages#index' 
 
  get 'about'      => 'pages#about'
  get 'contact'    => 'pages#contact'
  get 'signup'     => 'users#new'
  get 'login'      => 'sessions#new'
  get 'new'        => 'goals#new'
  
  
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  
  resources :users
  resources :goals, only: [:create, :edit, :destroy, :update]
  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goals, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper 
  
  private

    # Confirm the logged in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "You are not logged in. Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController   
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user,   only: :destroy
    
    def new
        @goal = Goal.new
    end
    
    
    def create
        @goal = current_user.goals.build(goals_params)
            if @goal.save
                flash[:success] = "Your goal has been successfully saved."
                redirect_to current_user
            else
                render root_url
            end    
    end
    
    def destroy
        @goal.destroy
        flash[:success] = "Your goal has been deleted."
        redirect_to request.referrer || root_url
    end
    
       
    def edit
       @goal = Goal.find(params[:id])
    end
    
    def update
        @goal = Goal.find(params[:id])
        if @goal.update(goals_params)
            flash[:succes] = "Your goal has been edited" 
            redirect_to current_user
        else
            render 'edit'
        end
    end
        
    private

    def goals_params
        params.require(:goal).permit(:name, :description)
    end
    
    def correct_user
      @goal = current_user.goals.find_by(id: params[:id])
      redirect_to root_url if @goal.nil?
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
 
      if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to root_url
      else
        flash.now[:danger] = 'The password or email address you have entered is invalid.'
        render 'new'
      end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @goals = @user.goals.paginate(page: params[:page])
  end

  def update
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Thanks for joining!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal  do |f| %>
    <p><%= f.text_field :name, placeholder: "Goal name" %> </p>
    <p><%= f.text_area :description, placeholder: "Description (optional)" %></p>
  <%= f.submit "Submit Goals", class: "btn btn-primary btn-xs" %>
<% end %>

app/views/goals/_goal.html.erb
<h2><%= goal.name %></h2> 

<blockquote>
    <p><%= goal.description %></p>
</blockquote>

<small>Started about <%= time_ago_in_words(goal.created_at) + ' ago' %></small> <br>
<%= link_to "edit", edit_goal_path(goal), class: "btn btn-info btn-xs" %>
<%= link_to "mark complete", edit_goal_path(goal), data: {confirm: "Mark Complete?" }, class: "btn btn-success btn-xs" %>
<%= link_to "delete", goal, method: :delete, data: { confirm: "Confirm Deletion" }, class: "btn btn-danger btn-xs" %>
<hr>

app/views/goals/edit.html.erb
<%= content_for :title, "Tally | New Goal" %>
<%= content_for :page_heading, "Submit a new goal" %>

<!-- For security, check if they are logged in first. -->

<% if logged_in? %>
<%= render 'form' %>
  
    <% else %>
<%= "It doesn't look like you are logged in. Please log in" %>
<% end %>

app/views/goals/new.html.erb
<%= content_for :title, "Tally | New Goal" %>
<%= content_for :page_heading, "Submit a new goal" %>

<!-- For security, check if they are logged in first. -->

<% if logged_in? %>
  <%= render 'form' %>
    <% else %>
<%= "It doesn't look like you are logged in. Please log in" %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted credit">&copy; Tally | Russell Christensen </p>
  </div>
</div>
</div>

app/views/layouts/_header.html.erb
<div id="wrap">
  
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          
        </button>
        <%= link_to 'Tally', root_path, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', root_path %></li>
       
         <% if logged_in? %>
        
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", current_user %></li>
              <li><%= link_to 'New Goal', new_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to 'Signup', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
          <% end %>
          <li><%= link_to 'About', about_path %></li>
          
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<!-- Begin page content -->
  <div class="container">
    <div class="page-header">
      <h1><%= yield(:page_heading) %></h1>
    </div>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    
  </div>
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<%= content_for :title, "Tally | About" %>
<%= content_for :page_heading, "About" %>
 <p>Created for the <a href="http://hackathon.slashrocket.io" title="Code Launch 2015" target="_blank">Code Launch 2015</a> by <a href="http://slashrocket.io" title="Slash Rocket Web Development Community" target="_blank">Slash Rocket</a>, Tally is a simple and intuitive time management and goal setting web application. 
  </p>

app/views/pages/contact.html.erb
<%= content_for :title, "Tally | Contact" %>
<%= content_for :page_heading, "Contact" %>

app/views/pages/index.html.erb
<%= content_for :title, "Tally | Home" %>
<%= content_for :page_heading do %>
<%=  "Tally" %> 
<span class="glyphicon glyphicon-check" aria-hidden="true"></span>

<% end %>


  
<div class="row">
  <div class="col-md-8"><p>Tally  is the result of the <a href="http://hackathon.slashrocket.io" title="Code Launch 2015" target="_blank">Code Launch 2015</a> hackathon from the web development community, <a href="http://slashrocket.io" title="Slash Rocket Web Development Community" target="_blank">Slash Rocket</a>. </p>
<p>The objective is simple: a time management application that helps you track your goals.</p></div>
  <div class="col-md-4"></div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<%= content_for :title, "Tally | Signup" %>
<%= content_for :page_heading, "Signup as new user" %>

<h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

app/views/users/show.html.erb
<% content_for :title do %>
<%= "Tally | " %> <%= @user.name.titleize %>
<% end %>

<!-- Show the page heading with the capitalized possessive user name --> 
<% content_for :page_heading do %> 
<%= @user.name.titleize.possessive %>
<%= "Dashboard" %>
<% end %>

<!-- Show (render) all of the goals and paginate them if the user has any -->
    <% if @user.goals.any? %>
      <h3>Total Goals <span class="badge badge-success"><%= @user.goals.count %></span></h3>
      <!-- Show amount of completed goals -->
      <h5>Completed Goals (<%= @user.goals.select {|r| r.completed}.size %>) </h5>
      <ol>
        <%= render @goals %>
      </ol>
      <%= will_paginate @goals%>
    <% end %>
  